setwd('/dssg/home/acct-medcl1/medcl1/Ovarian_carcinoma_GSE184880/HGSOC5/analysis')

OvarianCarcinoma=Read10X_h5('/dssg/home/acct-medcl1/medcl1/Ovarian_carcinoma_GSE184880/HGSOC5/cellranger/outs/filtered_feature_bc_matrix.h5')
OvarianCarcinoma=CreateSeuratObject(OvarianCarcinoma)
OvarianCarcinoma=NormalizeData(OvarianCarcinoma)
OvarianCarcinoma=FindVariableFeatures(OvarianCarcinoma)
OvarianCarcinoma=ScaleData(OvarianCarcinoma)
OvarianCarcinoma=RunPCA(OvarianCarcinoma)
OvarianCarcinoma=FindNeighbors(OvarianCarcinoma)
OvarianCarcinoma=FindClusters(OvarianCarcinoma)
OvarianCarcinoma=RunUMAP(OvarianCarcinoma,dims = 1:10)
DimPlot(OvarianCarcinoma,label = T)
FeaturePlot(OvarianCarcinoma,features = 'PTPRC')

OvarianCarcinomablood=NormalizeData(OvarianCarcinomablood)
OvarianCarcinomablood=FindVariableFeatures(OvarianCarcinomablood)
OvarianCarcinomablood=ScaleData(OvarianCarcinomablood)
OvarianCarcinomablood=RunPCA(OvarianCarcinomablood)
OvarianCarcinomablood=FindNeighbors(OvarianCarcinomablood)
OvarianCarcinomablood=FindClusters(OvarianCarcinomablood)
OvarianCarcinomablood=RunUMAP(OvarianCarcinomablood,dims = 1:10)
DimPlot(OvarianCarcinomablood,label = T)

OvarianCarcinomablooddata=OvarianCarcinomablood@assays$RNA@data
gene=c('CD34','PTPRC','CD38','ITGA6','FLT3','IL3RA','THY1','MME','CD3D','CD3E','CD3G','CD4','CD8A','CD36','TFRC','GYPA','ITGA2B','ITGB3','GP1BA','GP9','CD19','CD14','CD2','SDC1','CD7','IL7R','NCAM1','FCGR3A','ENPP3','CD63','FUT4','CD68','CD163','KIT','CD33','ITGAM','CSF1R','CSF2RA','FLT3','CLEC12A','FCGR1A','CD2','CD5','CD163','CD1C','THBD','LILRA4','GZMB','IL3RA','CLEC9A','FLT3','IDO1','HLA-DQA1','LAMP3','CCR7','FSCN1','FCER1A')
OvarianCarcinomablooddata=OvarianCarcinomablooddata[gene,]
OvarianCarcinomablooddata=as.data.frame(OvarianCarcinomablooddata)
OvarianCarcinomablooddata=t(OvarianCarcinomablooddata)
OvarianCarcinomablooddata=as.data.frame(OvarianCarcinomablooddata)
write.csv(OvarianCarcinomablooddata,'./OvarianCarcinomablooddata.csv')


S6bloodcells=S6blood@meta.data
S6bloodcells$cells=rownames(S6bloodcells)
S6bloodcells=merge(S6bloodcells,ColorectalCancer_B,by.x='cells',by.y='V1',all.x=T)
S6bloodcells=merge(S6bloodcells,ColorectalCancer_DC,by.x='cells',by.y='V1',all.x=T)
S6bloodcells=merge(S6bloodcells,ColorectalCancer_gran,by.x='cells',by.y='V1',all.x=T)
S6bloodcells=merge(S6bloodcells,ColorectalCancer_Mery,by.x='cells',by.y='V1',all.x=T)
S6bloodcells=merge(S6bloodcells,ColorectalCancer_monocytes,by.x='cells',by.y='V1',all.x=T)
S6bloodcells=merge(S6bloodcells,ColorectalCancer_neutrophils,by.x='cells',by.y='V1',all.x=T)
S6bloodcells=merge(S6bloodcells,ColorectalCancer_NK,by.x='cells',by.y='V1',all.x=T)
S6bloodcells=merge(S6bloodcells,ColorectalCancer_progenitor,by.x='cells',by.y='V1',all.x=T)
S6bloodcells=merge(S6bloodcells,ColorectalCancer_T,by.x='cells',by.y='V1',all.x=T)
S6bloodcells=S6bloodcells[,c(1,2,12:21)]
colnames(S6bloodcells)=c('cells','orig','clusters','B','DC','GRAN','ERY','MONO','NEU','NK','PRO','T')
S6bloodcells$type=paste(S6bloodcells$B,S6bloodcells$DC,sep = '/')
S6bloodcells$type=gsub('/NA','',S6bloodcells$type)
S6bloodcells$type=gsub('NA/','',S6bloodcells$type)
S6bloodcells$type=paste(S6bloodcells$type,S6bloodcells$GRAN,sep = '/')
S6bloodcells$type=gsub('/NA','',S6bloodcells$type)
S6bloodcells$type=gsub('NA/','',S6bloodcells$type)
S6bloodcells$type=paste(S6bloodcells$type,S6bloodcells$ERY,sep = '/')
S6bloodcells$type=gsub('/NA','',S6bloodcells$type)
S6bloodcells$type=gsub('NA/','',S6bloodcells$type)
S6bloodcells$type=paste(S6bloodcells$type,S6bloodcells$MONO,sep = '/')
S6bloodcells$type=gsub('/NA','',S6bloodcells$type)
S6bloodcells$type=gsub('NA/','',S6bloodcells$type)
S6bloodcells$type=paste(S6bloodcells$type,S6bloodcells$NEU,sep = '/')
S6bloodcells$type=gsub('/NA','',S6bloodcells$type)
S6bloodcells$type=gsub('NA/','',S6bloodcells$type)
S6bloodcells$type=paste(S6bloodcells$type,S6bloodcells$NK,sep = '/')
S6bloodcells$type=gsub('/NA','',S6bloodcells$type)
S6bloodcells$type=gsub('NA/','',S6bloodcells$type)
S6bloodcells$type=paste(S6bloodcells$type,S6bloodcells$PRO,sep = '/')
S6bloodcells$type=gsub('/NA','',S6bloodcells$type)
S6bloodcells$type=gsub('NA/','',S6bloodcells$type)
S6bloodcells$type=paste(S6bloodcells$type,S6bloodcells$T,sep = '/')
S6bloodcells$type=gsub('/NA','',S6bloodcells$type)
S6bloodcells$type=gsub('NA/','',S6bloodcells$type)

top20=BC.markers %>% group_by(cluster) %>% top_n(n = 20, wt = avg_log2FC)

S6bloodcells$type=gsub('/13','',S6bloodcells$type)
S6bloodcells$type=gsub('/12','',S6bloodcells$type)
S6bloodcells$type=gsub('/11','',S6bloodcells$type)
S6bloodcells$type=gsub('/10','',S6bloodcells$type)
S6bloodcells$type=gsub('/9','',S6bloodcells$type)
S6bloodcells$type=gsub('/8','',S6bloodcells$type)
S6bloodcells$type=gsub('/7','',S6bloodcells$type)
S6bloodcells$type=gsub('/6','',S6bloodcells$type)
S6bloodcells$type=gsub('/5','',S6bloodcells$type)
S6bloodcells$type=gsub('/4','',S6bloodcells$type)
S6bloodcells$type=gsub('/3','',S6bloodcells$type)
S6bloodcells$type=gsub('/2','',S6bloodcells$type)
S6bloodcells$type=gsub('/1','',S6bloodcells$type)
S6bloodcells$type=gsub('/0','',S6bloodcells$type)



NONbloodmeta2=as.data.frame(setdiff(Thyroidallbloodmeta$cells,Thyroidmeta$cells))
NONbloodmeta2=as.data.frame(setdiff(NONbloodmeta2$`setdiff(Thyroidallbloodmeta$cells, Thyroidmeta$cells)`,ThyroidNONbloodmeta$cells))
colnames(NONbloodmeta2)='cells'
NONblood2=subset(Thyroidallblood,cells =NONbloodmeta2$cells)
NONblood2data=NONblood2@assays$RNA@data
gene=c('CD34','PTPRC','CD38','ITGA6','FLT3','IL3RA','THY1','MME','CD3D','CD3E','CD3G','CD4','CD8A','CD36','TFRC','GYPA','ITGA2B','ITGB3','GP1BA','GP9','CD19','CD14','CD2','SDC1','CD7','IL7R','NCAM1','FCGR3A','ENPP3','CD63','FUT4','CD68','CD163','KIT','CD33','ITGAM','CSF1R','CSF2RA','FLT3','CLEC12A','FCGR1A','CD2','CD5','CD163','CD1C','THBD','LILRA4','GZMB','IL3RA','CLEC9A','FLT3','IDO1','HLA-DQA1','LAMP3','CCR7','FSCN1','FCER1A')
NONblood2data=NONblood2data[gene,]
NONblood2data=as.data.frame(t(as.data.frame(NONblood2data)))
write.csv(NONblood2data,'NONblood2data.csv')
S6bloodcells=NONblood2@meta.data
S6bloodcells$cells=rownames(S6bloodcells)
S6bloodcells=merge(S6bloodcells,NONblood2_B,by.x='cells',by.y='V1',all.x=T)
S6bloodcells=merge(S6bloodcells,NONblood2_DC,by.x='cells',by.y='V1',all.x=T)
S6bloodcells=merge(S6bloodcells,NONblood2_gran,by.x='cells',by.y='V1',all.x=T)
S6bloodcells=merge(S6bloodcells,NONblood2_Mery,by.x='cells',by.y='V1',all.x=T)
S6bloodcells=merge(S6bloodcells,NONblood2_monocytes,by.x='cells',by.y='V1',all.x=T)
S6bloodcells=merge(S6bloodcells,NONblood2_neutrophils,by.x='cells',by.y='V1',all.x=T)
S6bloodcells=merge(S6bloodcells,NONblood2_NK,by.x='cells',by.y='V1',all.x=T)
S6bloodcells=merge(S6bloodcells,NONblood2_progenitor,by.x='cells',by.y='V1',all.x=T)
S6bloodcells=merge(S6bloodcells,NONblood2_T,by.x='cells',by.y='V1',all.x=T)
S6bloodcells=S6bloodcells[,c(1,6:15)]
colnames(S6bloodcells)=c('cells','clusters','B','DC','GRAN','ERY','MONO','NEU','NK','PRO','T')
S6bloodcells$type=paste(S6bloodcells$B,S6bloodcells$DC,sep = '/')
S6bloodcells$type=gsub('/NA','',S6bloodcells$type)
S6bloodcells$type=gsub('NA/','',S6bloodcells$type)
S6bloodcells$type=paste(S6bloodcells$type,S6bloodcells$GRAN,sep = '/')
S6bloodcells$type=gsub('/NA','',S6bloodcells$type)
S6bloodcells$type=gsub('NA/','',S6bloodcells$type)
S6bloodcells$type=paste(S6bloodcells$type,S6bloodcells$ERY,sep = '/')
S6bloodcells$type=gsub('/NA','',S6bloodcells$type)
S6bloodcells$type=gsub('NA/','',S6bloodcells$type)
S6bloodcells$type=paste(S6bloodcells$type,S6bloodcells$MONO,sep = '/')
S6bloodcells$type=gsub('/NA','',S6bloodcells$type)
S6bloodcells$type=gsub('NA/','',S6bloodcells$type)
S6bloodcells$type=paste(S6bloodcells$type,S6bloodcells$NEU,sep = '/')
S6bloodcells$type=gsub('/NA','',S6bloodcells$type)
S6bloodcells$type=gsub('NA/','',S6bloodcells$type)
S6bloodcells$type=paste(S6bloodcells$type,S6bloodcells$NK,sep = '/')
S6bloodcells$type=gsub('/NA','',S6bloodcells$type)
S6bloodcells$type=gsub('NA/','',S6bloodcells$type)
S6bloodcells$type=paste(S6bloodcells$type,S6bloodcells$PRO,sep = '/')
S6bloodcells$type=gsub('/NA','',S6bloodcells$type)
S6bloodcells$type=gsub('NA/','',S6bloodcells$type)
S6bloodcells$type=paste(S6bloodcells$type,S6bloodcells$T,sep = '/')
S6bloodcells$type=gsub('/NA','',S6bloodcells$type)
S6bloodcells$type=gsub('NA/','',S6bloodcells$type)
NONblood2cells_macro=S6bloodcells[S6bloodcells$type=='Macrophage',]
NONblood2cells_cd4=S6bloodcells[S6bloodcells$type=='CD4+T',]
NONblood2_macro=subset(Thyroidallblood,cells=NONblood2cells_macro$cells)
NONblood2_cd4=subset(Thyroidallblood,cells=NONblood2cells_cd4$cells)
NONblood2_macro$type='Macrophage'
NONblood2_macro$aggregate='NON'
NONblood2_cd4$type='CD4+T'
NONblood2_cd4$aggregate='NON'
saveRDS(NONblood2_macro,'NONblood2_macro.rds')
saveRDS(NONblood2_cd4,'NONblood2_cd4.rds')
